### ISSUE TITLE
Cannot login - do you validate the login?

### ISSUE THREAD

**Issue by EugenMayer** [mlabouardy/nexus-cli#4]
using https://mynexus.tld and 'mydocker' as repo ( the name inside nexus ) but i get a 401 response all the way.

when running configure, is the login actually checked?

**Comment by worp1900** [comment]
Having the same problem. Did you find a solution @EugenMayer?

    $ nexus-cli configure
    Enter Nexus Host: https://my-repo:8082
    Enter Nexus Repository Name: docker-main
    Enter Nexus Username: nexus-cli
    Enter Nexus Password: myPassword
    $ nexus-cli image ls
    HTTP Code: 401

Logging into Nexus via the GUI with the provided credentials works.

Sidenote: Major necro, I know. But the problems are the same.

**Comment by EugenMayer** [comment]
@worp1900 i forked the project and yes its working for me

**Comment by worp1900** [comment]
@EugenMayer roger roger, thx! I'll check your version.

**Comment by worp1900** [comment]
Works like a charm and some powerful improvements you've made! Cheers!

**Comment by EugenMayer** [comment]
There is a lot in the network one could still merge in, a lot of good aditions like regexp support and all this - i wished i would have pulled them in by now - but at least it's a solid start for now :)
