### ISSUE TITLE
unability to actually delete images

### ISSUE THREAD

**Issue by aleksystasiak** [mlabouardy/nexus-cli#9]
nexus-cli is able to list images and tags

> root@nexus:~# ./nexus-cli image tags -name api-builder
> 1
> 10
> 11
> 12
> 13
> 14
> 15
> 16
> 17
> 18
> 19
> 2
> 3
> 4
> 5
> 6
> 7
> 8
> 9

but unable to delete them:
root@nexus:~# ./nexus-cli image delete -name api-builder -keep 2

> api-builder:1 image will be deleted ...
> api-builder:10 image will be deleted ...
> api-builder:11 image will be deleted ...
> api-builder:12 image will be deleted ...
> api-builder:13 image will be deleted ...
> api-builder:14 image will be deleted ...
> api-builder:15 image will be deleted ...
> api-builder:16 image will be deleted ...
> api-builder:17 image will be deleted ...
> api-builder:18 image will be deleted ...
> api-builder:19 image will be deleted ...
> api-builder:2 image will be deleted ...
> api-builder:3 image will be deleted ...
> api-builder:4 image will be deleted ...
> api-builder:5 image will be deleted ...
> api-builder:6 image will be deleted ...
> api-builder:7 image will be deleted ...

After running this command, nothing changes inside repository.
Tested under nexus 3.7.1-02 and 3.9.0-01

**Comment by aleksystasiak** [comment]
It seems my problem were caused by using wrong api version

**Comment by Frank111** [comment]
We have the same problem, how to solve it
